import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { colors, colorsP3, semantic } from "../src/tokens/colors.ts";
import { components } from "../src/tokens/components.ts";
import {
  breakpoints,
  container,
  motion,
  radius,
  shadows,
  spacing,
} from "../src/tokens/layout.ts";
import { STEPS } from "../src/tokens/ramp.ts";
import { fontStacks, typography } from "../src/tokens/typography.ts";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "src", "theme.generated.css");

const px = (n: number) => `${n}px`;

function colorVars(theme: "light" | "dark", indent: string) {
  const c = colors[theme];
  const lines: string[] = [];
  lines.push(`${indent}--color-background-100: ${c.background[100]};`);
  lines.push(`${indent}--color-background-200: ${c.background[200]};`);
  for (const [name, ramp] of [
    ["gray", c.gray],
    ["gray-alpha", c.grayAlpha],
    ["amber", c.amber],
    ["blue", c.blue],
    ["red", c.red],
    ["green", c.green],
  ] as const) {
    for (const step of STEPS)
      lines.push(`${indent}--color-${name}-${step}: ${ramp[step]};`);
  }
  for (const [name, ramp] of Object.entries(colorsP3[theme])) {
    for (const step of STEPS) {
      lines.push(
        `${indent}--color-${name}-${step}-p3: ${ramp[step as never]};`,
      );
    }
  }
  // Semantic aliases, so CSS can name the *role* instead of guessing a step.
  // Without these, a stylesheet has to hardcode `--color-blue-700` for a link,
  // which silently disagrees with design.md the moment a role points elsewhere
  // (dark links are blue-900, not blue-700).
  for (const [k, v] of Object.entries(semantic[theme])) {
    lines.push(`${indent}--color-${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(shadows[theme])) {
    lines.push(`${indent}--shadow-${k}: ${v};`);
  }
  return lines.join("\n");
}

const staticVars = [
  ...Object.entries(fontStacks).map(
    ([k, v]) => `  --font-${k.split(" ")[1].toLowerCase()}: ${v};`,
  ),
  "",
  ...Object.entries(spacing).map(([k, v]) => `  --spacing-${k}: ${px(v)};`),
  "",
  ...Object.entries(container).map(([k, v]) => `  --container-${k}: ${px(v)};`),
  "",
  ...Object.entries(breakpoints).map(
    ([k, v]) => `  --breakpoint-${k}: ${px(v)};`,
  ),
  "",
  ...Object.entries(radius).map(([k, v]) => `  --radius-${k}: ${px(v)};`),
  "",
  `  --ease-sunny: ${motion.easing};`,
  ...Object.entries(motion.duration).map(
    ([k, v]) => `  --duration-${k}: ${v}ms;`,
  ),
  "",
  ...Object.entries(typography).flatMap(([name, t]) => [
    `  --text-${name}: ${px(t.fontSize)};`,
    `  --text-${name}--line-height: ${px(t.lineHeight)};`,
    `  --text-${name}--font-weight: ${t.fontWeight};`,
    ...("letterSpacing" in t && t.letterSpacing
      ? [`  --text-${name}--letter-spacing: ${px(t.letterSpacing)};`]
      : []),
    `  --text-${name}--font-family: var(--font-${t.fontFamily.split(" ")[1].toLowerCase()});`,
  ]),
].join("\n");

const componentVars = Object.entries(components)
  .flatMap(([name, spec]) =>
    "height" in spec ? [`  --size-${name}: ${px(spec.height as number)};`] : [],
  )
  .join("\n");

const css = `/*
 * GENERATED by packages/sunny/scripts/build-theme.mts — do not edit.
 * Source of truth is packages/sunny/src/tokens/*.ts. Run \`pnpm theme\` to rebuild.
 */

/*
 * \`static\` because a plain \`@theme\` only emits the variables some utility
 * happens to reference. Nothing uses a \`shadow-sm\` class, so \`--shadow-sm\` was
 * dropped from :root and \`box-shadow: var(--shadow-sm)\` computed to \`none\` — but
 * only in light mode, since the dark values are emitted as ordinary :root rules
 * below and were never subject to tree-shaking. A design system publishes its
 * variables for other code to name; it can't know in advance which ones get used.
 */
@theme static {
${staticVars}

${componentVars}

  /* Light theme is the default. */
${colorVars("light", "  ")}
}

@media (prefers-color-scheme: dark) {
  :root {
${colorVars("dark", "    ")}
  }
}

:root[data-theme="dark"] {
${colorVars("dark", "  ")}
}

:root[data-theme="light"] {
${colorVars("light", "  ")}
}
`;

await mkdir(dirname(out), { recursive: true });
await writeFile(out, css, "utf8");
console.log(`theme.generated.css written (${css.split("\n").length} lines)`);
